worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 8043;

        proxy_set_header Cookie $http_cookie;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            root /usr/share/nginx/html;
            access_log off;
            expires 1M;
            add_header Cache-Control "public";
        }

        location ~* \.(woff2?|eot|ttf|otf)$ {
            root /usr/share/nginx/html;
        }
    }
}
