import type { components } from "./generated/sicol-api";

export type PaginaProcesosSelectivos = components["schemas"]["PaginaProcesosSelectivos"];
export type ProcesoSelectivo = components["schemas"]["ProcesoSelectivo"];
export type ProcesoSelectivoCreate = components["schemas"]["ProcesoSelectivoCreate"];
export type ProcesoSelectivoPatch = components["schemas"]["ProcesoSelectivoPatch"];
export type Examen = components["schemas"]["Examen"];
export type ExamenCreate = components["schemas"]["ExamenCreate"];
export type ExamenPatch = components["schemas"]["ExamenPatch"];
export type PersonaOpositora = components["schemas"]["PersonaOpositora"];
export type ConvocadoExamen = components["schemas"]["ConvocadoExamen"];
export type EstadoAsistencia = components["schemas"]["EstadoAsistenciaConvocado"];
export type AsistenciaUpdate = components["schemas"]["AsistenciaConvocadoUpdate"];
export type Provincia = components["schemas"]["Provincia"];
export type Centro = components["schemas"]["Centro"];
export type Aula = components["schemas"]["Aula"];
export type ImportacionResultado = components["schemas"]["ImportacionOpositoresAulasResultado"];
export type ImportacionAviso = components["schemas"]["ImportacionOpositoresAulasAviso"];
export type ApiError = components["schemas"]["Error"];
export type LoginRequest = components["schemas"]["LoginRequest"];
export type LoginResponse = components["schemas"]["LoginResponse"];
export type AuthenticatedUser = components["schemas"]["AuthenticatedUser"];
export type Oep = components["schemas"]["Oep"];
export type OepCreateUpdate = components["schemas"]["OepCreateUpdate"];
export type TipoAcceso = components["schemas"]["TipoAcceso"];
export type TipoAccesoCreateUpdate = components["schemas"]["TipoAccesoCreateUpdate"];
export type TipoVinculacion = components["schemas"]["TipoVinculacion"];
export type TipoVinculacionCreateUpdate = components["schemas"]["TipoVinculacionCreateUpdate"];
export type Cuerpo = components["schemas"]["Cuerpo"];
export type CuerpoCreateUpdate = components["schemas"]["CuerpoCreateUpdate"];
export type Colaborador = components["schemas"]["Colaborador"];
export type ColaboradorCreate = components["schemas"]["ColaboradorCreate"];
export type ColaboradorPatch = components["schemas"]["ColaboradorPatch"];
export type PaginaColaboradores = components["schemas"]["PaginaColaboradores"];
export type EstadoColaborador = components["schemas"]["EstadoColaborador"];
export type CambioEstadoColaboradores = components["schemas"]["CambioEstadoColaboradores"];
export type SexoColaborador = components["schemas"]["SexoColaborador"];
export type PerfilColaboracion = components["schemas"]["PerfilColaboracion"];
export type PerfilColaboracionCreateUpdate = components["schemas"]["PerfilColaboracionCreateUpdate"];
export type ImportacionColaboradoresResultado = components["schemas"]["ImportacionColaboradoresResultado"];
export type ImportacionAsignacionesHistoricasResultado = components["schemas"]["ImportacionAsignacionesHistoricasResultado"];
export type AsignacionColaborador = components["schemas"]["AsignacionColaborador"];
export type AsignacionColaboradorCreate = components["schemas"]["AsignacionColaboradorCreate"];
export type AsignacionColaboradorPatch = components["schemas"]["AsignacionColaboradorPatch"];
export type CambioHorasAsignaciones = components["schemas"]["CambioHorasAsignaciones"];
export type EstadoConfirmacionAsignacion = components["schemas"]["EstadoConfirmacionAsignacion"];
export type ContextoAsignacion = components["schemas"]["ContextoAsignacion"];
export type ExamenAula = components["schemas"]["ExamenAula"];
export type CentroExamen = components["schemas"]["CentroExamen"];
export type ResumenColaboraciones = components["schemas"]["ResumenColaboraciones"];
export type HojasFirma = components["schemas"]["HojasFirma"];
export type PagosColaboradores = components["schemas"]["PagosColaboradores"];
export type ConfiguracionInformes = components["schemas"]["ConfiguracionInformes"];
export type ConfiguracionInformesUpdate = components["schemas"]["ConfiguracionInformesUpdate"];
export type UsuarioAdmin = components["schemas"]["UsuarioAdmin"];
export type UsuarioAdminCreateUpdate = components["schemas"]["UsuarioAdminCreateUpdate"];
export type UsuarioRol = components["schemas"]["UsuarioRol"];
export type ColaboradorPortalPatch = components["schemas"]["ColaboradorPortalPatch"];
export type ConfirmacionAsignacionPortalUpdate = components["schemas"]["ConfirmacionAsignacionPortalUpdate"];
export type ImportacionProcesosResultado = components["schemas"]["ImportacionProcesosSelectivosResultado"];
export type ImportacionDatamartResultado = components["schemas"]["ImportacionDatamartConvocatoriasResultado"];
export type ImportacionDatamartAviso = components["schemas"]["ImportacionDatamartConvocatoriasAviso"];
export type CuadroMandoAdministracion = components["schemas"]["CuadroMandoAdministracion"];
export type CuadroMandoEjercicio = components["schemas"]["CuadroMandoEjercicio"];

export interface ImportacionArchivos {
  procesoSelectivoId: string;
  examenId: string;
  ficheroSirhus: File;
  ficheroCaronte?: File | null;
}
